include $(THEOS)/makefiles/common.mk

TWEAK_NAME = EffectsPlus
EffectsPlus_FILES = Tweak.xm CINone.m
EffectsPlus_FRAMEWORKS = AssetsLibrary CoreImage QuartzCore
EffectsPlus_PRIVATE_FRAMEWORKS = PhotoLibrary PhotoLibraryServices

include $(THEOS_MAKE_PATH)/tweak.mk